### ISSUE TITLE
Pyspark RESOURCE_LIMIT_EXCEEDED error

### ISSUE THREAD

**Issue by YannOrieult-EngieDigital** [delta-io/delta-sharing#109]
Hi,
I am not sure this issue is related to delta-sharing, but I can not use any more delta-sharing from Spark because of the systematic error:
```
22/01/14 22:10:51 INFO DataSourceStrategy: Pruning directories with:
22/01/14 22:10:51 INFO FileSourceStrategy: Pushed Filters:
22/01/14 22:10:51 INFO FileSourceStrategy: Post-Scan Filters:
22/01/14 22:10:51 INFO FileSourceStrategy: Output Data Schema: struct<_id: struct<oid: string>, assetID: string, attributeID: string, count: int, data: array<struct<complexValue:struct<value:string>,ts:timestamp,value:string>> ... 6 more fields>
22/01/14 22:10:51 INFO CodeGenerator: Code generated in 181.774052 ms
22/01/14 22:10:51 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 194.5 KiB, free 434.2 MiB)
22/01/14 22:10:52 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 34.5 KiB, free 434.2 MiB)
22/01/14 22:10:52 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on skymac-c02z30nnlvcf.home:53134 (size: 34.5 KiB, free: 434.4 MiB)
22/01/14 22:10:52 INFO SparkContext: Created broadcast 0 from showString at NativeMethodAccessorImpl.java:0
Traceback (most recent call last):
  File "spark-delta-sharing_extract.py", line 30, in <module>
    df.show()
  File "/usr/local/Cellar/apache-spark/3.2.0/libexec/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 494, in show
  File "/usr/local/Cellar/apache-spark/3.2.0/libexec/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1309, in __call__
  File "/usr/local/Cellar/apache-spark/3.2.0/libexec/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
  File "/usr/local/Cellar/apache-spark/3.2.0/libexec/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o28.showString.
: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting double-quote to start field name
 at [Source: (String)"{{"errorCode":"RESOURCE_LIMIT_EXCEEDED","message":"The table metadata size exceeded limits"}"; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1814)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:713)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:191)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:206)
	at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:205)
	at io.delta.sharing.spark.util.JsonUtils$$anon$1.readValue(JsonUtils.scala:26)
	at io.delta.sharing.spark.util.JsonUtils$.fromJson(JsonUtils.scala:38)
	at io.delta.sharing.spark.DeltaSharingRestClient.$anonfun$getFiles$1(DeltaSharingClient.scala:216)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at io.delta.sharing.spark.DeltaSharingRestClient.getFiles(DeltaSharingClient.scala:216)
	at io.delta.sharing.spark.RemoteSnapshot.filesForScan(RemoteDeltaLog.scala:197)
	at io.delta.sharing.spark.RemoteDeltaFileIndex.listFiles(RemoteDeltaLog.scala:266)
	at org.apache.spark.sql.execution.FileSourceScanExec.selectedPartitions$lzycompute(DataSourceScanExec.scala:234)
	at org.apache.spark.sql.execution.FileSourceScanExec.selectedPartitions(DataSourceScanExec.scala:229)
	at org.apache.spark.sql.execution.FileSourceScanExec.dynamicallySelectedPartitions$lzycompute(DataSourceScanExec.scala:264)
	at org.apache.spark.sql.execution.FileSourceScanExec.dynamicallySelectedPartitions(DataSourceScanExec.scala:245)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD$lzycompute(DataSourceScanExec.scala:432)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD(DataSourceScanExec.scala:417)
	at org.apache.spark.sql.execution.FileSourceScanExec.doExecute(DataSourceScanExec.scala:495)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:184)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.InputAdapter.inputRDD(WholeStageCodegenExec.scala:526)
	at org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs(WholeStageCodegenExec.scala:454)
	at org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs$(WholeStageCodegenExec.scala:453)
	at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:497)
	at org.apache.spark.sql.execution.ProjectExec.inputRDDs(basicPhysicalOperators.scala:50)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:750)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:184)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:325)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:443)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:429)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:48)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3715)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2728)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3706)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3704)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2728)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2935)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:287)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:326)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)

22/01/14 22:11:07 INFO SparkContext: Invoking stop() from shutdown hook
22/01/14 22:11:07 INFO SparkUI: Stopped Spark web UI at http://skymac-c02z30nnlvcf.home:4040
22/01/14 22:11:07 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
22/01/14 22:11:07 INFO MemoryStore: MemoryStore cleared
22/01/14 22:11:07 INFO BlockManager: BlockManager stopped
22/01/14 22:11:07 INFO BlockManagerMaster: BlockManagerMaster stopped
22/01/14 22:11:07 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
22/01/14 22:11:07 INFO SparkContext: Successfully stopped SparkContext
22/01/14 22:11:07 INFO ShutdownHookManager: Shutdown hook called
```
The code looks like
```
delta_sharing_conf_path = "/path/conf.share"

share = "test"
schema = "schema"
table = "table"

table_path = delta_sharing_conf_path + f"#{share}.{schema}.{table}"

sc = SparkContext('local')
spark = SparkSession(sc)

df = spark.read.format("deltaSharing").load(table_path)
df.show()
```

The issue concerns all commands with spark and the packages `io.delta:delta-sharing-spark_2.12:0.2.0`. I have the same error with `pyspark --packages io.delta:delta-sharing-spark_2.12:0.2.0` with the same basic commands.

I was able to request and access data from Spark delta-sharing on the 13th of January but not anymore.

I am using a MacBook Pro 2019 up-to-date, with apache-spark (3.2.0) and openjdk@11 (11.0.12).

**Comment by zhuansunxt** [comment]
Hi @YannOrieult-EngieDigital  

Error message shows `The table metadata size exceeded limits`. It means your delta log is too big to handle on the delta sharing server.

Where is the sharing server running? You can manually create checkpoint if you using Delta Lake OSS or you can run some [optimizations](https://docs.databricks.com/delta/optimizations/file-mgmt.html) e.g. `OPTIMIZE` if you are using Databricks

**Comment by YannOrieult-EngieDigital** [comment]
Hi,
Thanks for the return. Indeed, the message was explicit. An `OPTIMIZE` fixed this issue.
This issue can be closed.

**Comment by francisco-ltech** [comment]
Hi @zhuansunxt - Is there a recommended size the delta log shouldn't exceed?
