### ISSUE TITLE
Unable to specify hadoop configuration for AWS S3 Access on Delta Server

### ISSUE THREAD

**Issue by patrickjmccauley** [delta-io/delta-sharing#118]
We are working on standing up a delta sharing server on an AWS EC2 VM using docker and pulling data from S3. However, despite trying a variety of things, including passing in environmental variables to the `docker run` command and dropping a `core-site.xml` file with our access/secret keys in `/opt/docker/conf` with the `HADOOP_CONF_DIR` set to that folder, we continue to receive the below error:

```
46904 [armeria-common-worker-epoll-2-1] WARN org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
47620 [armeria-common-worker-epoll-2-1] ERROR io.delta.sharing.server.DeltaSharingServiceExceptionHandler - com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentExceptio
n: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
io.delta.sharing.server.DeltaInternalException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified
 by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
        at io.delta.sharing.server.DeltaSharingService.processRequest(DeltaSharingService.scala:104)
        at io.delta.sharing.server.DeltaSharingService.getMetadata(DeltaSharingService.scala:159)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:338)
        at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$2(AnnotatedService.java:285)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
        at com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve0(AnnotatedService.java:289)
        at com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve(AnnotatedService.java:262)
        at com.linecorp.armeria.server.RouteDecoratingService.serve(RouteDecoratingService.java:92)
        at com.linecorp.armeria.server.RouteDecoratingService.serve(RouteDecoratingService.java:67)
        at com.linecorp.armeria.server.auth.AuthService.handleSuccess(AuthService.java:118)
        at com.linecorp.armeria.server.auth.AuthService.lambda$serve$0(AuthService.java:99)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:522)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId
and fs.s3.awsSecretAccessKey properties (respectively).
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3849)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4688)
        at io.delta.standalone.internal.DeltaSharedTableLoader.loadTable(DeltaSharedTableLoader.scala:49)
        at io.delta.sharing.server.DeltaSharingService.$anonfun$getMetadata$1(DeltaSharingService.scala:162)
        at io.delta.sharing.server.DeltaSharingService.processRequest(DeltaSharingService.scala:101)
        ... 27 more
Caused by: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
        at org.apache.hadoop.fs.s3.S3Credentials.initialize(S3Credentials.java:74)
```
We are running the deltaio/delta-sharing-server:0.2.0 with the below command:
```bash
docker run -p 9999:9999 --mount type=bind,source=/home/ubuntu/config.yaml,target=/config/delta-sharing-server-config.yaml --mount type=bind,source=/home/ubuntu/core-siget=/opt/docker/conf/core-site.xml  -e HADOOP_CONF_DIR=/opt/docker/conf  deltaio/delta-sharing-server:0.2.0 -- --config /config/delta-sharing-server-config.yaml
```

We can successfully curl the all-tables endpoints, but any that attempt to connect to S3 return a 500 with the above error. We were hoping that the docker container would inherit IAM permissions from the EC2 instance, which can successfully retrieve from S3. However, when it appeared that was not the case, we tried using the IAM metadata provider as specified in the README. Is there something else that we're missing that needs to be set in order for the server to pick up the variables specified in our `core-site.xml` file?

```xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
  <property>
    <name>fs.s3n.awsAccessKeyId</name>
    <value>XXXX</value>
  </property>

  <property>
    <name>fs.s3n.awsSecretAccessKey</name>
    <value>XXXX</value>
  </property>
</configuration>
```

* Docker image: deltaio/delta-sharing-server:0.2.0 
* EC2 image: ubuntu-bionic-18.04-amd64-server
* IAM permissions on EC2:
```
"Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                ...
            ]
```

**Comment by patrickjmccauley** [comment]
We ended up realizing that our `config.yaml` had a table location beginning with `s3://` rather than `s3a://`
