### ISSUE TITLE
java.lang.NullPointerException when reading delta file on Google Cloud Storage 

### ISSUE THREAD

**Issue by anhvh1408** [delta-io/delta-sharing#127]
I have config.yaml like this:

```
version: 1
shares:
- name: "share1"
  schemas:
  - name: "default"
    tables:
    - name: "delta-table"
      location: "gs://xxxx/delta-table" #"gs://<bucket-name>/<the-table-path>"
host: "localhost"
port: 8080
endpoint: "/delta-sharing"
preSignedUrlTimeoutSeconds: 3600
deltaTableCacheSize: 10
stalenessAcceptable: false
evaluatePredicateHints: false
authorization:
  bearerToken: "abcabc"
```

, and already have Google Service Account key (which has permission to view Cloud Storage)

, and the gs://xxxx/delta-table is a delta table

, My docker run is like this (Docker Desktop on Mac M1):

```
docker run \
--volume=/tmp/keys/delta-sharing-9864a6b8425e.json:/tmp/keys/delta-sharing-9864a6b8425e.json \
--env=GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/delta-sharing-9864a6b8425e.json \
-p 8080:8080 -v /Users/lap02429/Downloads/delta_test/config:/mnt  --platform linux/amd64  deltaio/delta-sharing-server:0.4.0 -- --config /mnt/delta-sharing-server-config.yaml
```

And the image can run
but when I run this
```
table_url = profile_file + "#share1.default.delta-table"
data = delta_sharing.load_as_pandas(table_url)
print(data.head(10))
```

it has error like this:

```ERROR io.delta.sharing.server.DeltaSharingServiceExceptionHandler - java.lang.NullPointerException
io.delta.sharing.server.DeltaInternalException: java.lang.NullPointerException
	at io.delta.sharing.server.DeltaSharingService.processRequest(DeltaSharingService.scala:138)
	at io.delta.sharing.server.DeltaSharingService.listFiles(DeltaSharingService.scala:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:338)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$2(AnnotatedService.java:285)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve0(AnnotatedService.java:289)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve(AnnotatedService.java:262)
	at com.linecorp.armeria.server.RouteDecoratingService.serve(RouteDecoratingService.java:92)
	at com.linecorp.armeria.server.RouteDecoratingService.serve(RouteDecoratingService.java:67)
	at com.linecorp.armeria.server.auth.AuthService.handleSuccess(AuthService.java:118)
	at com.linecorp.armeria.server.auth.AuthService.lambda$serve$0(AuthService.java:99)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:522)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
	at com.google.cloud.storage.BlobId.of(BlobId.java:108)
	at io.delta.sharing.server.GCSFileSigner.sign(CloudFileSigner.scala:209)
	at io.delta.standalone.internal.DeltaSharedTable.$anonfun$query$2(DeltaSharedTableLoader.scala:165)
	at scala.collection.immutable.Stream.map(Stream.scala:418)
	at io.delta.standalone.internal.DeltaSharedTable.$anonfun$query$1(DeltaSharedTableLoader.scala:163)
	at io.delta.standalone.internal.DeltaSharedTable.withClassLoader(DeltaSharedTableLoader.scala:107)
	at io.delta.standalone.internal.DeltaSharedTable.query(DeltaSharedTableLoader.scala:133)
	at io.delta.sharing.server.DeltaSharingService.$anonfun$listFiles$1(DeltaSharingService.scala:232)
	at io.delta.sharing.server.DeltaSharingService.processRequest(DeltaSharingService.scala:135)
....
````

When I run with spark-shell:
````
val tablePath = "/Users/test.share#share1.default.delta-table"
val df = spark.read.format("deltaSharing").load(tablePath)
df.printSchema()
````
=> It still prints the schema of delta table in gcs, but can not print out the data, the error still the same that I pointed above: NullPointerException.

Can anyone help me with this? Thanks so so much!

**Comment by anhvh1408** [comment]
When I use spark-shell, the df schema can be printed out, but can not show the data.

**Comment by anhvh1408** [comment]
The problem is that if the bucket name has "_" character, it will fail. I will close issue.
