### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by nish4528** [delta-io/delta-sharing#53]
Whenever i am trying to read the delta table from s3 using load_as_pandas function i am getting a connection issue in ec2 instance. Following is the issue:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb6514c1c10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5044): Max retries exceeded with url: /delta-sharing/test/shares/share1/schemas/schema1/tables/table1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6514c1c10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.7/site-packages/delta_sharing/delta_sharing.py", line 61, in load_as_pandas
    rest_client=DataSharingRestClient(profile),
  File "/home/ec2-user/.local/lib/python3.7/site-packages/delta_sharing/reader.py", line 62, in to_pandas
    self._table, predicateHints=self._predicateHints, limitHint=self._limitHint
  File "/home/ec2-user/.local/lib/python3.7/site-packages/delta_sharing/rest_client.py", line 84, in func_with_retry
    raise e
  File "/home/ec2-user/.local/lib/python3.7/site-packages/delta_sharing/rest_client.py", line 77, in func_with_retry
    return func(self, *arg, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/delta_sharing/rest_client.py", line 182, in list_files_in_table
    f"/shares/{table.share}/schemas/{table.schema}/tables/{table.name}/query", data=data,
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/delta_sharing/rest_client.py", line 204, in _request_internal
    response = request(f"{self._profile.endpoint}{target}", json=data)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5044): Max retries exceeded with url: /delta-sharing/test/shares/share1/schemas/schema1/tables/table1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6514c1c10>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by zsxwing** [comment]
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5044): Max retries exceeded with url: /delta-sharing/test/shares/share1/schemas/schema1/tables/table1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6514c1c10>: Failed to establish a new connection: [Errno 111] Connection refused'))

This error means the connector cannot talk to `127.0.0.1:5044`. Is it the right address? Where do you run the delta sharing server? If you are using docker, you need to use the host name or ip address of your docker container.

**Comment by nish4528** [comment]
Yes that is the address. I am running the delta sharing server using this command bin/delta-sharing-server -- --config <the-server-config-yaml-file> locally. Is there any other way to run the server?

**Comment by nish4528** [comment]
Hi. yes that is the address. I am trying to run the server locally using this command bin/delta-sharing-server -- --config <the-server-config-yaml-file>. Is there any other way to run the server? i tried using docker also but i faced some permission issue

**Comment by zsxwing** [comment]
> bin/delta-sharing-server -- --config

Did the server start successfully? The end of the logs should output the address that the server is using. Could you check it?

**Comment by zsxwing** [comment]
> No FileSystem for scheme "s3"

You need to use `s3a` in the table path. But I think you have solved it since you can read the table schema.

> requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5044): Max retries exceeded with url: /delta-sharing/test/shares/share1/schemas/schema1/tables/table1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6514c1c10>: Failed to establish a new connection: [Errno 111] Connection refused'))

Did you see any logs in the server side when this happened?

**Comment by nish4528** [comment]
I am not sure from where to check the logs.

**Comment by nish4528** [comment]
No there were no logs there when this error came in ec2

**Comment by zsxwing** [comment]
@nish4528 have you solved the issue? When you run `bin/delta-sharing-server -- --config`, it's supposed to output logs to the  terminator. Here is an example of these logs:

```
2583 [pool-1-thread-1] INFO com.linecorp.armeria.common.Flags - com.linecorp.armeria.tlsAllowUnsafeCiphers: false (default)
2584 [pool-1-thread-1] INFO com.linecorp.armeria.common.Flags - com.linecorp.armeria.transientServiceOptions:  (default)
2590 [pool-1-thread-1] INFO com.linecorp.armeria.common.Flags - com.linecorp.armeria.useLegacyRouteDecoratorOrdering: false (default)
2590 [pool-1-thread-1] INFO com.linecorp.armeria.common.Flags - Using nio
3478 [pool-1-thread-1] INFO com.linecorp.armeria.common.Flags - com.linecorp.armeria.useOpenSsl: true (default)
3538 [pool-1-thread-1] INFO com.linecorp.armeria.common.Flags - Using OpenSSL: BoringSSL, 0x1010107f
3538 [pool-1-thread-1] INFO com.linecorp.armeria.common.Flags - com.linecorp.armeria.dumpOpenSslInfo: false (default)
3784 [armeria-boss-https-*:12345] INFO com.linecorp.armeria.server.Server - Serving HTTPS at /0:0:0:0:0:0:0:0:12345 - https://127.0.0.1:12345/
```

**Comment by nish4528** [comment]
It was resolved
