### ISSUE TITLE
Using the delta-sharing library from Anaconda Python Installation

### ISSUE THREAD

**Issue by alison199** [delta-io/delta-sharing#80]
Hi,

I'm trying to use the delta-sharing library from JupyterHub

- If I try to use a Python installation from a centos machine, load_as_pandas() works

- If I use an Anaconda Python installation with load_as_pandas() I get a FileNotFoundError. I've tried installing the delta-sharing and pyarrow libraries with conda-forge rather than pip, but I still get the same error

Is there anything additional that I need for the delta-sharing Anaconda installation ?

Thank you very much

**Comment by zsxwing** [comment]
Could you post the entire FileNotFoundError?

**Comment by alison199** [comment]
>>> delta_sharing.load_as_pandas(table_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/delta_sharing/delta_sharing.py", line 59, in load_as_pandas
    return DeltaSharingReader(
  File "/opt/conda/lib/python3.7/site-packages/delta_sharing/reader.py", line 73, in to_pandas
    [DeltaSharingReader._to_pandas(file, converters) for file in response.add_files],
  File "/opt/conda/lib/python3.7/site-packages/delta_sharing/reader.py", line 73, in <listcomp>
    [DeltaSharingReader._to_pandas(file, converters) for file in response.add_files],
  File "/opt/conda/lib/python3.7/site-packages/delta_sharing/reader.py", line 95, in _to_pandas
    dataset(source=add_file.url, format="parquet", filesystem=filesystem)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 671, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 428, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 404, in _ensure_single_source
    raise FileNotFoundError(path)
FileNotFoundError: https://s3_endpoint/bucket_name/dataset_table/file-00003-4fe05f6b-9aa9-4561-8723-6e43d36132d1-c000.parquet?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20211123T113539Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=credential%2F20211123%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=ef3738c09d75cd6a5cd7860ce9299d1b0965bf52a078132ee575fc8ac438ca68

**Comment by alison199** [comment]
The other questions I have are:

1) How do you pass multiple login credentials to S3 ? Can the server only use one S3 username/password combination ?

2) How do you pass filters to the load_as_pandas() and load_as_spark() method based on the printSchema fields (field= value) ? Then we can get less data as the datasets are huge

**Comment by alison199** [comment]
The other questions I was thinking about:

- Can the same server accept incoming requests from multiple users at the same time ?
- Can this library be used for any dataset in S3 ? For some datasets we have in S3 I've checked the server logs and it says for example 'This is not a Delta table'. Does that mean that we can only fetch data in S3 for datasets that have a Delta like table ?

**Comment by zsxwing** [comment]
The error looks like a bug in some specific version of some library. Could you provide the versions of the following libraries for Anaconda Python installation?

- pyarraw
- fsspec
- pandas

You can just run the following commands:

```
>>> import pyarrow
>>> pyarrow.__version__
'4.0.0'
>>> import fsspec
>>> fsspec.__version__
'0.7.4'
>>> import pandas
>>> pandas.__version__
'1.2.4'
```

> * How do you pass multiple login credentials to S3 ? Can the server only use one S3 username/password combination ?

You can config credentials for each S3 bucket when using Delta Sharing 0.2.0 or above. You can create a Hadoop configuration file named `core-site.xml` and add it to the server's `conf` directory. Then add the content to the xml file following this instruction: https://hadoop.apache.org/docs/r2.10.1/hadoop-aws/tools/hadoop-aws/index.html#Configuring_different_S3_buckets

If you run the server in an EC2 instance, applications running in EC2 may associate an IAM role with the VM and query the [EC2 Instance Metadata Service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) for credentials to access S3.

> How do you pass filters to the load_as_pandas() and load_as_spark() method based on the printSchema fields (field= value) ? Then we can get less data as the datasets are huge

- `load_as_pandas` doesn't support it as it will load the entire dataset to the memory. 
- `load_as_spark` supports projections or filters. If you use `load_as_spark`, we will leverage Spark to optimize the queries to fetch less data.

> * Can the same server accept incoming requests from multiple users at the same time ?

Yes

> * Can this library be used for any dataset in S3 ? For some datasets we have in S3 I've checked the server logs and it says for example 'This is not a Delta table'. Does that mean that we can only fetch data in S3 for datasets that have a Delta like table ?

Currently Delta Sharing Server only supports Delta tables. If you have a parquet table, you can check this page to convert it to a Delta table: https://docs.delta.io/latest/delta-utility.html#convert-a-parquet-table-to-a-delta-table

**Comment by alison199** [comment]
Thank you zsxwing for all the information.

I'm using the following. Should I be using different versions ?

```
import pyarrow
print(pyarrow.__version__)
import fsspec
print(fsspec.__version__)
import pandas
print(pandas.__version__)

6.0.1
2021.11.1
1.3.4
```
The FileNotFoundError only seems to happen with Anaconda. If I install python from source with configure, make, make install, then it works as you can see below.

![image](https://user-images.githubusercontent.com/13468919/144409385-cb79f091-048f-4c16-8f94-8cabc8b8f341.png)

I've tried configuring multiple S3 buckets but I get the below error if I use fs.s3a.bucket.BUCKET_NAME.access.key/fs.s3a.bucket.BUCKET_NAME.secret.key in my core-site.xml. It only works if I use fs.s3a.access.key/fs.s3a.secret.key. 
----------------------------------------------------------------------------
`Caused by: com.amazonaws.AmazonClientException: No AWS Credentials provided by BasicAWSCredentialsProvider EnvironmentVariableCredentialsProvider InstanceProfileCredentialsProvider : com.amazonaws.SdkClientException: The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/`
---------------------------------------------------------------------------------
The other question I have is the following:

- I'm using a JupyterHub setup that launches single user notebooks. Each user has their own Json Web Token (JWT). This means some users may only be able to access some of our datasets in S3 and others all our datasets for example. Does the delta-sharing server allow this user type access? I'm thinking of the following parts that load the delta-sharing server:

endpoint: "/delta-sharing"
authorization:
  bearerToken: xxx

If users had a different bearerToken, would a different delta-sharing server pod have to be created for each user rather than a central one for all users ? 

For example we have created a dataset reader endpoint and we pass as a query argument the users authorization token as follows:

https://department/reader/dataset?auth_token=users_authorization_token
